#!/usr/bin/env bash

set -e

start=$PWD
timestamp=`date +%s`
tmpremote=/tmp/deploy-test/"$timestamp"_remote
tmpdir=/tmp/deploy-test/"$timestamp"

#cd "$start"

../init "$tmpremote"

mkdir -p "$tmpdir"
cd "$tmpdir"
git init

git status
git remote add deploy "$tmpremote"/git
date >> times.log
git add times.log
git commit times.log -m 'commit 1'
echo 'commited one file'
git status
git remote -v
git push deploy master

echo test $tmpremote/master 
test -e $tmpremote/master
#echo expected times.log
ls $tmpremote/master
diff times.log $tmpremote/master/times.log

#create a tag
git tag -a master_stable -m 'master_stable tag'
git push deploy --tags

diff times.log $tmpremote/master_stable/times.log

#git checkout -b testbranch
#git branch

#exit 0

date >> times.log
git add times.log
git commit times.log -m 'commit 2'

date >> times.log
git add times.log
git commit times.log -m 'commit 3'

#date >> times.log
#git add times.log
#git commit times.log -m 'commit 4'

git push deploy master
diff times.log $tmpremote/master/times.log
git log

echo PASSED

